version: '3'

services:
  app:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    container_name: teste-son
    tty: true
    restart: always
    ports:
      - 3001:3001
    volumes:
      - .:/home/node/app
